# Generated by Django 5.2.13 on 2026-04-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
