# Generated by Django 6.0.3 on 2026-05-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
        ('core', '0006_service_phone_number'),
    ]

    operations = [
    ]
