# Generated by Django 5.2.13 on 2026-05-04 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_booking_service_request'),
        ('core', '0010_post'),
    ]

    operations = [
    ]
